// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAbgWNUwBhsm5nqjwpBOiZlXpYuBTrV-s',
    appId: '1:800993691351:web:82553c783a0b853e9d9292',
    messagingSenderId: '800993691351',
    projectId: 'flutter-prep-a6f64',
    authDomain: 'flutter-prep-a6f64.firebaseapp.com',
    databaseURL: 'https://flutter-prep-a6f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-a6f64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8JVd5-2sZb2BEkdXxcthG1pJXlakq8Kg',
    appId: '1:800993691351:android:8aa1971ac44db5569d9292',
    messagingSenderId: '800993691351',
    projectId: 'flutter-prep-a6f64',
    databaseURL: 'https://flutter-prep-a6f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-a6f64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6YR4W7kDfCauMKUWog2et3OaQyJhIRXs',
    appId: '1:800993691351:ios:126f5eba46bf46cb9d9292',
    messagingSenderId: '800993691351',
    projectId: 'flutter-prep-a6f64',
    databaseURL: 'https://flutter-prep-a6f64-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-a6f64.firebasestorage.app',
    androidClientId: '800993691351-2cvmaf9odlktj97gt55tj0bkiuqc0j66.apps.googleusercontent.com',
    iosClientId: '800993691351-iiciooa4taaoqs8o75tjs3g4ce3moflf.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalReferralUi',
  );
}
